fix: fix issue where languages card is empty when no languages are detected
RoadieHQ/roadie-backstage-plugins pull request #691
Opened 2022-10-19 16:28 UTC by Brend-Smits

Small bug fix, in some cases when GitHub has not detected any languages used in a repository, the language card will be empty like:  
<img width="372" alt="image" src="https://user-images.githubusercontent.com/15904543/196749952-04540b55-1943-47ee-845b-0753250d61a3.png">

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [x] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

2022-10-20 11:55 UTC, kissmikijr requested changes
Nice! Thank you for the fix, can you add a changeset ? A patch bump would be good.

2022-10-20 12:09 UTC, Brend-Smits commented
@kissmikijr, done! Sorry about that..

2022-10-24 08:52 UTC, kissmikijr commented
@Brend-Smits one of the test fails, can you fix that and after it's ready to ship!

2022-10-24 08:54 UTC, Brend-Smits commented
Yep will do @kissmikijr. Quite busy at this moment, but will try my best. If you are able to do it before I get to it, feel free to commit to this branch.

2022-11-09 19:10 UTC, punkle commented on plugins/frontend/backstage-plugin-github-insights/src/components/Widgets/LanguagesCard/LanguagesCard.tsx
> +    alertApi.post({ message: error.message, severity: 'error' });
Will it be obvious which of the many plugins rendered to the page, which plugin is erroring here?

2022-11-10 07:38 UTC, Xantier submitted a review, later dismissed

2022-11-10 12:11 UTC, kissmikijr approved these changes

2022-11-10 12:15 UTC, merged