feat: replace moment by dayJS
RoadieHQ/roadie-backstage-plugins pull request #829
Opened 2023-01-26 10:35 UTC by Tragio

Hi 👋 

I noticed that our app was bundling `moment` (72kb gzipped) and I found that was your amazing plugin importing it.

This PR aims to replace `moment` with `dayjs`. Perhaps this could be made using native JS but I don't have the full picture and `dayjs` is a `moment` replacement with the same API.

https://bundlephobia.com/package/moment@2.29.4
https://bundlephobia.com/package/dayjs@1.11.7

The savings should be around 93% from 72kb (gzipped) to ~4kb (gzipped). Please test and make sure all is working properly 🙏 

Most probably you are also using moment in other plugins and if makes sense could be also a good idea to replace them also.

Thank you for the amazing work 🙂 

#### :heavy_check_mark: Checklist

- [ ] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

2023-01-26 10:40 UTC, Xantier commented on plugins/frontend/backstage-plugin-github-pull-requests/.changeset/sixty-apples-cough.md
> +'@roadiehq/backstage-plugin-github-pull-requests': minor
This looks to be a patch change since it doesn't introduce new functionality or breaking changes.

2023-01-26 10:41 UTC, Xantier requested changes
The upstream community for Backstage has settled on using `Luxon` as the canonical temporal management library. I know the bundle size is a bit larger than `dayjs` but we should move towards that one instead of introducing another one.

2023-01-26 11:03 UTC, Tragio commented
@Xantier ahh ok awesome. Should I change the PR for it or do you prefer to make your own pull request on it, since you know the background of everything and perhaps is quicker? 🤔

2023-01-26 11:04 UTC, Xantier commented
If you could modify this PR, that would be great!

2023-01-27 09:26 UTC, Tragio commented
@Xantier make sure all is ok. I also noticed that Luxon doesn't have any equivalent to `humanize()`. I picked the most active one, let me know if you want to change it. 😄

2023-01-30 14:39 UTC, Xantier approved these changes
Nice! Thanks.

2023-01-30 14:47 UTC, Xantier commented
Few tweaks to go before merging. Looks to be failing type check on CI

2023-03-31 11:11 UTC, punkle commented
We havent heard from you in a few weeks @Tragio so I have created a new pull request building on your changes here https://github.com/RoadieHQ/roadie-backstage-plugins/pull/922

2023-04-12 08:31 UTC, closed without merging