chore: enhance argoCD delete operation to handle exceptions better
RoadieHQ/roadie-backstage-plugins pull request #847
Opened 2023-02-10 20:45 UTC by sbellam1187

#### :heavy_check_mark: Checklist

- [x] Added tests for new functionality and regression tests for bug fixes
- [x] Added changeset (run `yarn changeset` in the root)
- [ ] Screenshots of before and after attached (for UI changes)
- [ ] Added or updated documentation (if applicable)

fixes: https://github.com/RoadieHQ/roadie-backstage-plugins/issues/846

2023-02-13 16:03 UTC, sbellam1187 commented
The changes part of the PR are around argocd backend plugin and haven't touched any other plugin, but some UI tests are failing.

2023-02-14 09:02 UTC, kissmikijr commented
Retriggered the failed job, not sure what's going on.

2023-02-16 08:39 UTC, kissmikijr requested changes
Thank you! Just some small tweaks

2023-02-16 13:02 UTC, kissmikijr commented on plugins/backend/backstage-plugin-argo-cd-backend/src/service/router.ts
> +          isAppexist = false;
```suggestion
          isAppExist = false;
```

2023-02-16 13:02 UTC, kissmikijr commented on plugins/backend/backstage-plugin-argo-cd-backend/src/service/router.ts
> +      if (isAppexist) {
```suggestion
      if (isAppExist) {
```

2023-02-16 13:03 UTC, kissmikijr commented on plugins/backend/backstage-plugin-argo-cd-backend/src/service/router.ts
> +          } catch (e: any) {
Can we please log the original exception ?

2023-02-17 17:14 UTC, kissmikijr requested changes
just one more thing and ready to go!

2023-02-17 17:14 UTC, kissmikijr commented on .changeset/six-tips-study.md
> +'@roadiehq/backstage-plugin-argo-cd-backend': major
```suggestion
'@roadiehq/backstage-plugin-argo-cd-backend': minor
```
A minor version bump should be enough, what do you think? Are we introducing breaking change here?

2023-02-20 21:50 UTC, sbellam1187 commented
Merged latest changes from main branch and observing few tests are failing with the changes not part of the the PR. How to proceed with the change? @karlhaworth

2023-02-21 09:40 UTC, kissmikijr approved these changes
I think it is ready to merge, @karlhaworth any more thoughts on this?

2023-02-21 14:56 UTC, kissmikijr commented
Let's ship it

2023-02-21 14:56 UTC, merged